# Generated by Django 4.2.17 on 2024-12-18 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_remove_product_category_delete_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
